/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptormetamodel.DomainObject;
import sculptormetamodel.Module;
import sculptormetamodel.Subscribe;

/**
 * A sample validator interface for {@link sculptormetamodel.Consumer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConsumerValidator {
	boolean validate();

	boolean validateModule(Module value);
	boolean validateRepositoryDependencies(EList value);
	boolean validateServiceDependencies(EList value);
	boolean validateChannel(String value);
	boolean validateMessageRoot(DomainObject value);
	boolean validateOtherDependencies(EList value);
	boolean validateSubscribe(Subscribe value);
}
