/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.DiscriminatorType;
import sculptormetamodel.InheritanceType;

/**
 * A sample validator interface for {@link sculptormetamodel.Inheritance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InheritanceValidator {
	boolean validate();

	boolean validateDiscriminatorColumnName(String value);
	boolean validateDiscriminatorColumnLength(String value);
	boolean validateType(InheritanceType value);
	boolean validateDiscriminatorType(DiscriminatorType value);
}
