/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptormetamodel.Application;

/**
 * A sample validator interface for {@link sculptormetamodel.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateBasePackage(String value);
	boolean validateApplication(Application value);
	boolean validateDomainObjects(EList value);
	boolean validateConsumers(EList value);
	boolean validateServices(EList value);
	boolean validateExternal(boolean value);
	boolean validatePersistenceUnit(String value);
	boolean validateResources(EList value);
}
