/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.Event;

/**
 * A sample validator interface for {@link sculptormetamodel.Publish}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublishValidator {
	boolean validate();

	boolean validateEventBus(String value);
	boolean validateTopic(String value);
	boolean validateEventType(Event value);
}
