/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.DomainObject;
import sculptormetamodel.Reference;

/**
 * A sample validator interface for {@link sculptormetamodel.Reference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceValidator {
	boolean validate();

	boolean validateMany(boolean value);
	boolean validateCollectionType(String value);
	boolean validateOpposite(Reference value);
	boolean validateTo(DomainObject value);
	boolean validateCascade(String value);
	boolean validateOrderBy(String value);
	boolean validateVisibility(String value);
	boolean validateChangeable(boolean value);
	boolean validateFrom(DomainObject value);
	boolean validateRequired(boolean value);
	boolean validateFetch(String value);
	boolean validateCache(boolean value);
	boolean validateNaturalKey(boolean value);
	boolean validateInverse(boolean value);
	boolean validateNullable(boolean value);
	boolean validateDatabaseColumn(String value);
	boolean validateValidate(String value);
	boolean validateTransient(boolean value);
	boolean validateDatabaseJoinTable(String value);
	boolean validateDatabaseJoinColumn(String value);
}
