/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.Repository;

/**
 * A sample validator interface for {@link sculptormetamodel.RepositoryOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RepositoryOperationValidator {
	boolean validate();

	boolean validateDelegateToAccessObject(boolean value);
	boolean validateRepository(Repository value);
	boolean validateAccessObjectName(String value);
}
