/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptormetamodel.Module;

/**
 * A sample validator interface for {@link sculptormetamodel.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
	boolean validate();

	boolean validateServiceDependencies(EList value);
	boolean validateGapClass(boolean value);
	boolean validatePath(String value);
	boolean validateOperations(EList value);
	boolean validateModule(Module value);
}
