/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.HttpMethod;
import sculptormetamodel.Resource;
import sculptormetamodel.ServiceOperation;

/**
 * A sample validator interface for {@link sculptormetamodel.ResourceOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceOperationValidator {
	boolean validate();

	boolean validateResource(Resource value);
	boolean validatePath(String value);
	boolean validateHttpMethod(HttpMethod value);
	boolean validateDelegate(ServiceOperation value);
	boolean validateReturnString(String value);
}
