/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptormetamodel.validation;

import sculptormetamodel.RepositoryOperation;
import sculptormetamodel.Service;
import sculptormetamodel.ServiceOperation;

/**
 * A sample validator interface for {@link sculptormetamodel.ServiceOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceOperationValidator {
	boolean validate();

	boolean validateDelegate(RepositoryOperation value);
	boolean validateService(Service value);
	boolean validateServiceDelegate(ServiceOperation value);
}
