/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import sculptormetamodel.ServiceOperation;

/**
 * A sample validator interface for {@link sculptorguimetamodel.DeleteTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeleteTaskValidator {
	boolean validate();

	boolean validateFindDOWith(ServiceOperation value);
	boolean validateDeleteDOWith(ServiceOperation value);
}
