/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;


/**
 * A sample validator interface for {@link sculptorguimetamodel.DisplayMessageBehavior}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DisplayMessageBehaviorValidator {
	boolean validate();

	boolean validateMessage(String value);
	boolean validateCancelable(boolean value);

	boolean validateMessageId(String value);
}
