/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptorguimetamodel.GuiApplication;

import sculptormetamodel.Module;

/**
 * A sample validator interface for {@link sculptorguimetamodel.GuiModule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GuiModuleValidator {
	boolean validate();

	boolean validateUserTasks(EList value);
	boolean validateBasePackage(String value);
	boolean validateApplication(GuiApplication value);
	boolean validateFor(Module value);
	boolean validateViews(EList value);

	boolean validateEvents(EList value);

	boolean validateServiceDependencies(EList value);
}
