/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptorguimetamodel.GuiApplication;

import sculptorguimetamodel.StubModule;
import sculptormetamodel.Module;

/**
 * A sample validator interface for {@link sculptorguimetamodel.GuiModule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GuiModuleValidator {
	boolean validate();

	boolean validateUserTasks(EList value);
	boolean validateBasePackage(String value);
	boolean validateApplication(GuiApplication value);
	boolean validateFor(Module value);
	boolean validateViews(EList value);

	boolean validateEvents(EList value);

	boolean validateServiceDependencies(EList value);

	boolean validateServiceProxies(EList value);

	boolean validateCommands(EList value);

	boolean validateBehaviors(EList value);

	boolean validateConditions(EList value);

	boolean validateStubModule(StubModule value);

	boolean validateDtos(EList value);

	boolean validateStubModule(Module value);
}
