/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import sculptorguimetamodel.View;

/**
 * A sample validator interface for {@link sculptorguimetamodel.PopupPanelBehavior}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PopupPanelBehaviorValidator {
	boolean validate();

	boolean validateView(View value);

	boolean validatePanelName(String value);

	boolean validatePanelView(View value);
}
