/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import sculptormetamodel.Attribute;
import sculptormetamodel.DomainObjectOperation;
import sculptormetamodel.Reference;
import sculptorguimetamodel.PropertyReference;

/**
 * A sample validator interface for {@link sculptorguimetamodel.PropertyReferringWidget}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyReferringWidgetValidator {
	boolean validate();

	boolean validateForAttribute(Attribute value);

	boolean validateForReference(Reference value);

	boolean validateForOp(DomainObjectOperation value);

	boolean validateForProperty(PropertyReference value);

	boolean validateFor(PropertyReference value);
}
