/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptormetamodel.Service;

/**
 * A sample validator interface for {@link sculptorguimetamodel.ServiceProxy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceProxyValidator {
	boolean validate();

	boolean validateFor(Service value);
	boolean validateOperations(EList value);
}
