/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import org.eclipse.emf.common.util.EList;

import sculptormetamodel.Reference;

/**
 * A sample validator interface for {@link sculptorguimetamodel.TmpReferenceHolder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TmpReferenceHolderValidator {
	boolean validate();

	boolean validateReference(Reference value);
	boolean validateSubTaskTransitionHolders(EList value);
}
