/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package sculptorguimetamodel.validation;

import sculptorguimetamodel.TmpReferenceHolder;

import sculptormetamodel.DomainObject;

/**
 * A sample validator interface for {@link sculptorguimetamodel.TmpSubTaskTransitionHolder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TmpSubTaskTransitionHolderValidator {
	boolean validate();

	boolean validateToTaskType(String value);
	boolean validateTo(DomainObject value);
	boolean validateReferenceHoler(TmpReferenceHolder value);
}
