<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sculptorguimetamodel"
    nsURI="http://www.fornax-platform.org/sculptorgui" nsPrefix="sc">
  <eClassifiers xsi:type="ecore:EClass" name="GuiApplication" eSuperTypes="sculptormetamodel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guiForApplication" lowerBound="1"
        eType="ecore:EClass sculptormetamodel.ecore#//Application"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" lowerBound="1"
        upperBound="-1" eType="#//GuiModule" containment="true" eOpposite="#//GuiModule/application"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiModule" eSuperTypes="sculptormetamodel.ecore#//NamedElement #//BehaviorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTasks" lowerBound="1"
        upperBound="-1" eType="#//UserTask" containment="true" eOpposite="#//UserTask/module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//GuiApplication"
        eOpposite="#//GuiApplication/modules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" eType="ecore:EClass sculptormetamodel.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true" eOpposite="#//View/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//GuiEvent" containment="true" eOpposite="#//GuiEvent/guiModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceDependencies" upperBound="-1"
        eType="ecore:EClass sculptormetamodel.ecore#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//GuiCommand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stubModule" eType="#//StubModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserTask" eSuperTypes="sculptormetamodel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTaskTransitions" upperBound="-1"
        eType="#//SubTaskTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//GuiModule"
        eOpposite="#//GuiModule/userTasks"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewProperties" upperBound="-1"
        eType="#//ViewDataProperty" containment="true" eOpposite="#//ViewDataProperty/userTask"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversationRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gapClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="populateDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="findDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="populateDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="findDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="searchDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="findDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deleteDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubTaskTransition" eSuperTypes="sculptormetamodel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//UserTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forReference" lowerBound="1"
        eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//UserTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewDataProperty" eSuperTypes="sculptormetamodel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTask" eType="#//UserTask"
        eOpposite="#//UserTask/viewProperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TmpReferenceHolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTaskTransitionHolders"
        upperBound="-1" eType="#//TmpSubTaskTransitionHolder" containment="true" eOpposite="#//TmpSubTaskTransitionHolder/referenceHoler"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TmpSubTaskTransitionHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toTaskType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceHoler" lowerBound="1"
        eType="#//TmpReferenceHolder" eOpposite="#//TmpReferenceHolder/subTaskTransitionHolders"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceViewProperty" eSuperTypes="#//ViewDataProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTransitions" upperBound="-1"
        eType="#//SubTaskTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previewProperties" upperBound="-1"
        eType="#//ViewDataProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeViewProperty" eSuperTypes="#//ViewDataProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass sculptormetamodel.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTypeViewProperty" eSuperTypes="#//ViewDataProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass sculptormetamodel.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumViewProperty" eSuperTypes="#//ViewDataProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTypeEnumViewProperty" eSuperTypes="#//EnumViewProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicTypeReference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserTaskGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTasks" upperBound="-1"
        eType="#//UserTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//GuiModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedReferenceViewProperty" eSuperTypes="#//ReferenceViewProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedFrom" lowerBound="1"
        eType="#//ReferenceViewProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTask" eSuperTypes="#//UserTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="findDOWith" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//WidgetsContainer sculptormetamodel.ecore#//NamedElement #//BehaviorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//GuiModule"
        eOpposite="#//GuiModule/views"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceProxies" upperBound="-1"
        eType="#//ServiceProxy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ViewParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendsName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget" eSuperTypes="sculptormetamodel.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorBindings" lowerBound="1"
        upperBound="-1" eType="#//BehaviorBinding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabled" eType="#//UiCondition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visible" eType="#//UiCondition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputTextWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="InformationalTextWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonWidget" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReferringWidget" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forAttribute" eType="ecore:EClass sculptormetamodel.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forReference" eType="ecore:EClass sculptormetamodel.ecore#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forOp" eType="ecore:EClass sculptormetamodel.ecore#//DomainObjectOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableWidget" eSuperTypes="#//PropertyReferringWidget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//TableColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paging" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiEvent" eSuperTypes="sculptormetamodel.ecore#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guiModule" lowerBound="1"
        eType="#//GuiModule" eOpposite="#//GuiModule/events"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn" eSuperTypes="#//PropertyReferringWidget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextAreaWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutocompleteWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="RadioButtonsWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichTextAreaWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputDateWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberSpinnerWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProxy" eSuperTypes="sculptormetamodel.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="ecore:EClass sculptormetamodel.ecore#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guiModule" eType="#//GuiModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProxyOperation" eSuperTypes="sculptormetamodel.ecore#//ServiceOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="ecore:EClass sculptormetamodel.ecore#//ServiceOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiCommand" eSuperTypes="#//GuiDto"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewParameter" eSuperTypes="sculptormetamodel.ecore#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkWidget" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toView" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidgetsContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//Widget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PanelWidget" eSuperTypes="#//WidgetsContainer #//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiBehavior" eSuperTypes="sculptormetamodel.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PopulatePanelBehavior" eSuperTypes="#//UiBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="panel" lowerBound="1" eType="#//PanelWidget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigateToViewBehavior" eSuperTypes="#//UiBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" lowerBound="1"
        upperBound="-1" eType="#//UiBehavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnClickBinding" eSuperTypes="#//BehaviorBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnHoverBinding" eSuperTypes="#//BehaviorBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="UiCondition" eSuperTypes="sculptormetamodel.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="GuiDto" eSuperTypes="sculptormetamodel.ecore#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" eType="ecore:EClass sculptormetamodel.ecore#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guiModule" eType="#//GuiModule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiEnum" eSuperTypes="sculptormetamodel.ecore#//Enum #//GuiDto"/>
  <eClassifiers xsi:type="ecore:EClass" name="StubModule" eSuperTypes="sculptormetamodel.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stubFor" eType="ecore:EClass sculptormetamodel.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guiModule" lowerBound="1"
        eType="#//GuiModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListBoxWidget" eSuperTypes="#//PropertyReferringWidget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forEnum" lowerBound="1"
        eType="ecore:EClass sculptormetamodel.ecore#//Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//UiCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//UiBehavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomWidget" eSuperTypes="#//PropertyReferringWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateTableBehavior" eSuperTypes="#//UiBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//TableWidget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfirmMessageBehavior" eSuperTypes="#//UiBehavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomBehavior" eSuperTypes="#//UiBehavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomCondition" eSuperTypes="#//UiCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeBehavior" eSuperTypes="#//UiBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//UiBehavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnSelectItemBinding" eSuperTypes="#//BehaviorBinding"/>
</ecore:EPackage>
